//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachService
    {
        public long CoachServiceID { get; set; }
        public string CoachService1 { get; set; }
        public long CoachMasterID { get; set; }
        public long ServiceCategoryID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ServiceCategory ServiceCategory { get; set; }
    }
}
