//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public long EnquiryId { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public bool IsResponce { get; set; }
        public string Name { get; set; }
    }
}
