//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public long OTPID { get; set; }
        public string UniqueCode { get; set; }
        public string OTPCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
