//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMaster
    {
        public long StateMasterID { get; set; }
        public string StateName { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
    }
}
